### ISSUE TITLE
NullReference Exception when server is not running

### ISSUE THREAD

**Issue by sztupy** [Olivine-Labs/Alchemy-Websockets#50]
I'm trying to handle the case when the server is not available. Unfortunately Alchemy Client seems to crash with no possibility to catch the connection error:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Alchemy.WebSocketClient.Disconnect()
   at Alchemy.WebSocketClient.OnRunClient(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

All this in a spearate Thread after running:

```
aClient.Connect();
```

Is there any other way to catch this error so I could handle the case when the server is not available?

**Comment by vegazrelli** [comment]
The same for me!!! i'm getting crazy!!! No solution at the moment!

**Comment by sztupy** [comment]
Here is a fix for this: https://github.com/sztupy/Alchemy-Websockets

**Comment by ajacksified** [comment]
Unfortunately alchemy client is a little immature - we'll have to take a look at this.

@sztupy - if you have a fix, would you mind doing a pull request? Thanks!

**Comment by sztupy** [comment]
This pull should have fixed the problem as well in an other way: https://github.com/Olivine-Labs/Alchemy-Websockets/pull/55, so mine is obsolete now.
