### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by jknight** [Olivine-Labs/Alchemy-Websockets#60]
1) git clone
2) open in vs
3) (test driven .net) -> right click on Integration, run tests:

------ Test started: Assembly: AlchemyIntegrationTest.dll ------

Test 'Alchemy.ClientServer.ClientConnect' failed: System.NullReferenceException : Object reference not set to an instance of an object.
    at System.Net.Sockets.TcpClient.get_Connected()
    WebSocketClient.cs(53,0): at Alchemy.WebSocketClient.get_Connected()
    ClientServer.cs(59,0): at Alchemy.ClientServer.ClientConnect()

Test 'Alchemy.ClientServer.ClientSendData' failed: System.NullReferenceException : Object reference not set to an instance of an object.
    at System.Net.Sockets.TcpClient.get_Connected()
    WebSocketClient.cs(53,0): at Alchemy.WebSocketClient.get_Connected()
    ClientServer.cs(66,0): at Alchemy.ClientServer.ClientSendData()

Test 'Alchemy.ClientServer.ClientSendDataConcurrent' failed: System.NullReferenceException : Object reference not set to an instance of an object.
    at System.Net.Sockets.TcpClient.get_Connected()
    WebSocketClient.cs(53,0): at Alchemy.WebSocketClient.get_Connected()
    ClientServer.cs(78,0): at Alchemy.ClientServer.ClientSendDataConcurrent()

Test 'Alchemy.ClientServerSubProtocol.ClientShoulConnectWithSecondaryValidProtocol' failed: 
  Expected: True
  But was:  False
    ClientServerSubProtocol.cs(68,0): at Alchemy.ClientServerSubProtocol.ClientShoulConnectWithSecondaryValidProtocol()

Test 'Alchemy.ClientServerSubProtocol.ClientShoulConnectWithValidProtocol' failed: 
  Expected: True
  But was:  False
    ClientServerSubProtocol.cs(55,0): at Alchemy.ClientServerSubProtocol.ClientShoulConnectWithValidProtocol()

1 passed, 5 failed, 0 skipped, took 44.63 seconds (NUnit 2.5.10).

**Comment by lykme516** [comment]
I am experiencing the same problem running the integration tests with NUnit. I am unable to use the Websocket client library in my application because I always experience a System.NullReferenceException when attempting to connect. I dug a little deeper and I experience an exception in the SetupContext method.

Exception : "Cannot access a disposed object.\r\nObjectname: 'System.Net.Sockets/Socket'."

StackTrace:   

 at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   at Alchemy.WebSocketClient.SetupContext(Context context) in ..\Alchemy\WebSocketClient.cs:line 191

Has anyone been able to successfully create a websocket connection using the Websocket Client Library?

**Comment by jknight** [comment]
The last revision I could get to build out of the box was e7a55eec49ae6c5fa2d507f81264932201e64e2f, Oct 17th. It seems like the merges ofter Oct 17 broke the build.
